feat: more juicy stuff Bump: major

diff --git a/.github/workflows/bump_version.yaml b/.github/workflows/bump_version.yaml
--- a/.github/workflows/bump_version.yaml
+++ b/.github/workflows/bump_version.yaml
@@ -15,6 +15,17 @@ jobs:
           git config user.name "github-actions"
           git config user.email "github-actions@users.noreply.github.com"
 
+      - name: Decide bump type
+        id: decide_bump
+        run: |
+          COMMIT_MSG=$(git log -1 --pretty=%B)
+          BUMP_TYPE=$(python3 ./cicd_scripts/extract_bump_type.py "$COMMIT_MSG")
+          if [ "$BUMP_TYPE" = "error" ]; then
+            echo "Invalid bump type. FAILURE"
+            exit 1
+          fi
+          echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
+
       - name: Bump version
         id: bump_version
         run: |
